//Create new property
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_FAILURE = 'ADD_PROPERTY_FAILURE';

//Get Suburb suggestions
export const GET_SUBURB_SUGGESTIONS = 'GET_SUBURB_SUGGESTIONS';
export const UPDATE_SUBURB_SUGGESTION_INPUT_VALUE = 'UPDATE_SUBURB_SUGGESTION_INPUT_VALUE';
export const UPDATE_SUBURB_SUGGESTIONS = 'UPDATE_SUBURB_SUGGESTIONS';
export const CLEAR_SUBURB_SUGGESTIONS = 'CLEAR_SUBURB_SUGGESTIONS';

export const CHANGE_PRICE = 'CHANGE_PRICE';
export const CHANGE_BOND = 'CHANGE_BOND';
export const CHANGE_AVAILABLESTART = 'CHANGE_AVAILABLESTART';
export const CHANGE_MINTERM = 'CHANGE_MINTERM';
export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_DETAILS = 'CHANGE_DETAILS';
export const CHANGE_PROPERTYTYPE = 'CHANGE_PROPERTYTYPE';
export const CHANGE_ROOMTYPE = 'CHANGE_ROOMTYPE';
export const CHANGE_PROPERTYFEATURE = 'CHANGE_PROPERTYFEATURE';
export const CHANGE_FILES = 'CHANGE_FILES';
export const CHANGE_CONTACTNAME = 'CHANGE_CONTACTNAME';
export const CHANGE_CONTACTNUMBER = 'CHANGE_CONTACTNUMBER';
export const CHANGE_CONTACTEMAIL = 'CHANGE_CONTACTEMAIL';
export const CHANGE_CONTACTSOCIAL = 'CHANGE_CONTACTSOCIAL';

export const RESET_STATE = 'RESET_STATE';

// User actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_NOT_FOUND = 'USER_NOT_FOUND'
export const USER_FOUND = 'USER_NOT_FOUND'
export const USER_EXIST_IN_SESSION = 'USER_EXIST_IN_SESSION'
export const USER_NOT_IN_SESSION = 'USER_NOT_IN_SESSION'
